# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    
    resolvers:
        my_resolver:
            web_path:
                web_root: "%kernel.root_dir%"
                cache_prefix: "media/cache"

    filter_sets:
        cache: ~

        miniatures:
            quality: 70
            filters:
                relative_resize: 
                    widen: 500 # Shrink/upscale the image to 150 of height, with full quality 