vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
<<<<<<< HEAD
=======
    mappings:
        products_images:
            uri_prefix: '%app.path.images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            upload_destination: '%kernel.project_dir%/public%app.path.images%'
>>>>>>> 44382dbb7a6eedbdf33b20a02aecb1bbc3f3113d
